### ISSUE TITLE
Make a new view for individual Skynet links

### ISSUE THREAD

**Issue by tbenz9** [tbenz9/datanation.tech#3]
When a user clicks on a Skynet link they should be taken to a new page that displays all the known information about the file (call `files?fileLink=<skynetlink>`).  This new view should also have a "report"  and "mark as dead" button.  The report button will take the user to a new view with a short form to report the file and give some info about what it is being reported for.

We should also have a spot for comments below the general information.

Up to your discretion, but I think it would be cool to display a couple different download buttons for the different Skynet portals, different users may prefer a certain portal based on geographic location, etc.

**Comment by n8mgr** [comment]
Fixed by #4
